### ISSUE TITLE
Setup documentation?

### ISSUE THREAD

**Issue by gbanfalvikl** [OtherCrashOverride/go-play#1]
Would it be possible to add some basic documentation about how we can build this ourselves?

**Comment by OtherCrashOverride** [comment]
There is discussion about building here:
https://forum.odroid.com/viewtopic.php?f=159&t=31303#p226519

Feel free to note anything that needs further clarification.  The short explanation is that you set up an esp-idf build environment and then change into the directory of the project to build (nesemu-go, gnuboy-go, smsplus-go).  Each project is built the same as for any other esp-idf project (make).

**Comment by rickyzhang82** [comment]
@OtherCrashOverride 
Can you open a wiki here? I will copy your notes to move it to your repo.

**Comment by rickyzhang82** [comment]
@OtherCrashOverride Please allow others to create a wiki page. I can't do the leg work.

**Comment by OtherCrashOverride** [comment]
I changed the wiki setting.
