### ISSUE TITLE
[GBC] Pokémon Pinball bad refresh

### ISSUE THREAD

**Issue by puggile** [OtherCrashOverride/go-play#11]
I tried "Pokemon Pinball" game on GBC emulator and, with latest firmware (20180629-psram), I have some "refresh problem":

Ball "shakes" when it reaches the top or bottom of the display, before changing the game screen.

If you need more information please let me know.

**Comment by OtherCrashOverride** [comment]
I can reproduce the issue.

**Comment by OtherCrashOverride** [comment]
I have identified the issue and a fix is being tested.

**Comment by OtherCrashOverride** [comment]
Resolved by b0e8a2308633cc9346e0fd7f1ba49e0f3081dcd5
