### ISSUE TITLE
Use and display sub folders

### ISSUE THREAD

**Issue by Voljega** [OtherCrashOverride/go-play#15]
It might be good to be able to handle subfolders in rom directories, it facilitates the navigation (I personnaly use it to sort games by genre)
They could be shown and you could enter/exit them with A and B like systems

For now they are not recognised at all, games in subfolders simply not appear, nor the subfolders themselves

**Comment by OtherCrashOverride** [comment]
The issue with sub-folders is they add size to the path string.  This can cause an issue in the emulators where the RAM is very limited.  Therefore, I do not plan to support this feature for the technical reason stated.

**Comment by Voljega** [comment]
oh ok, thank you for the response, I wasn't aware ram size and handling was that critical

**Comment by Voljega** [comment]
What about limiting folder name to three chars ?

**Comment by OtherCrashOverride** [comment]
It would lead to customer confusion if an arbitrary limit was used.  There is no indication of the limitation or explanation of why a folder does not show.

I should point out that its possible for anyone to write their own menu program with the features they desire.
