### ISSUE TITLE
Go to the end of the list

### ISSUE THREAD

**Issue by Voljega** [OtherCrashOverride/go-play#16]
For now it's not possible to go directly to the end of the list of roms of a system.

It can be done like in other distributions interface (EmulationStation, if I must name it) by going up on the first game of the list

It might also help to be able to go down or up the list by keeping left and right pressed, for now, you ahve to press / release / press / release etc...

**Comment by OtherCrashOverride** [comment]
See also #7.

**Comment by OtherCrashOverride** [comment]
This is implemented in the firmware release:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180708
