### ISSUE TITLE
GBC Failure to launch

### ISSUE THREAD

**Issue by joshschools** [OtherCrashOverride/go-play#19]
After flashing to this GBC freezes when launching. Blue bar completes green freezes at end.

**Comment by OtherCrashOverride** [comment]
Make sure to erase the flash before reflashing.

**Comment by joshschools** [comment]
I have erased multiple times and it still persists. Any other recommendations?

**Comment by joshschools** [comment]
Yup, totes user error. Mixed up the addresses. Keep up the great work!
