### ISSUE TITLE
Seeing roms twice.

### ISSUE THREAD

**Issue by Adem1987** [OtherCrashOverride/go-play#2]
I'm seeing the roms twice. One is normal and the other has ._filename. Why is that so?
I can't play the ones with dots.

**Comment by OtherCrashOverride** [comment]
https://discussions.apple.com/thread/1448575

**Comment by OtherCrashOverride** [comment]
This release should work around the issue with operating systems that create "hidden" files:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180629-psram

**Comment by OtherCrashOverride** [comment]
This should be resolved in the latest firmware release:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180708

Reopen this issue if it is not.
