### ISSUE TITLE
Add SD card error status icons.

### ISSUE THREAD

**Issue by OtherCrashOverride** [OtherCrashOverride/go-play#29]
Since the PSRAM update, all emulators use the SD card and need to indicate any error conditions.

**Comment by kamotswind** [comment]
Notes:
https://github.com/OtherCrashOverride/go-play/blob/master/odroid-go-common/components/odroid/odroid_display.c#L1273
https://github.com/OtherCrashOverride/go-play/blob/master/gnuboy-go/components/gnuboy/loader.c#L231

**Comment by OtherCrashOverride** [comment]
Resolved in release
https://github.com/OtherCrashOverride/go-play/releases/tag/20180712
