### ISSUE TITLE
Sort order is incorrect

### ISSUE THREAD

**Issue by OtherCrashOverride** [OtherCrashOverride/go-play#34]
Currently the file list is ASCII sorted.  This makes "Z" less than "a".

**Comment by kamotswind** [comment]
This is in the menu, correct?

**Comment by OtherCrashOverride** [comment]
Yes, the menu file selection list.

**Comment by OtherCrashOverride** [comment]
Fixed in release:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180712
