### ISSUE TITLE
[SMS] Video issue with Where in the World is Carmen Sandiego (USA)

### ISSUE THREAD

**Issue by kamotswind** [OtherCrashOverride/go-play#36]
While trying out a new game today that my wife requested I discovered an issue that may be refresh rate related like another issue reported. This occurs in most of the game so it should be easy to reproduce. Audio sounds perfectly fine.

I've attached a short video clip showing the issue.
![game-video-error](https://user-images.githubusercontent.com/7111675/42565822-8c6c8892-84d2-11e8-8fff-d2141e50affa.gif)

**Comment by OtherCrashOverride** [comment]
This should now work with the latest release:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180718-smsplusgx

**Comment by kamotswind** [comment]
It does, thanks!
