### ISSUE TITLE
Suggestion: embed images

### ISSUE THREAD

**Issue by Molorius** [OtherCrashOverride/go-play#37]
Just a suggestion: it is easily possible to embed images/audio/etc files rather than convert them into a large binary header (such as in odroid-go-common/components/odroid/image_*.h). [See the docs.](http://esp-idf.readthedocs.io/en/latest/api-guides/build-system.html#embedding-binary-data) I have found this easier to maintain, as you can quickly see what images are included. Nice project, by the way.

**Comment by OtherCrashOverride** [comment]
Embedding a binary is more "fragile" than embedding the image as a header file.  The header "self describes" the data being used and is produced atomically (by GIMP) ensuring the data layout (struct) always matches the data.

The esp-idf does not support any image formats.  Formats such as PNG are not suitable for use within the memory constraints.

**Comment by Molorius** [comment]
Makes sense, carry on. I also didn't know GIMP could do that, good to know.
