### ISSUE TITLE
[GG] Aerial Assault (World) won't load

### ISSUE THREAD

**Issue by kamotswind** [OtherCrashOverride/go-play#40]
The emulator seems to execute but it is just a blank screen with no audio. Resetting the emulator with power on while holding start doesn't make a difference.

**Comment by asiag0** [comment]
try resetting the system with Menu button instead of Start (Power Switch Off, Hold Menu, Power switch On, Release Menu when Main Menu appears)

this game? [https://imgur.com/a/4G6rKo3](https://imgur.com/a/4G6rKo3)

might just be a bad rom.  the file i have seems to play just fine, though I suck at the game.

**Comment by Adem1987** [comment]
No, there are a lot of roms with the [!] tag but they don’t work.

**Comment by kamotswind** [comment]
I've reset using both methods, should have mentioned that. It could be a bad rom which I didn't think about since I haven't had that happen before :) I'll give a new one a try and report back.

**Comment by kamotswind** [comment]
@asiag0 What firmware version are you on?

**Comment by OtherCrashOverride** [comment]
For SMS/GG, the most likely cause of an issue is either timing or lack of mapper support.  I searched but could not locate the mapper used by the game.  If it is a non-standard, support will need to be added.

**Comment by kamotswind** [comment]
That's fine. I thought it may be something simple so if it turns out not to be then I'll just close this issue.

**Comment by OtherCrashOverride** [comment]
The title works with this:
https://github.com/OtherCrashOverride/Genesis-Plus-GX-crashoverride

So, the answer is somewhere in there.

**Comment by DavidKnight247** [comment]
Genesis plus go has a lot of rom mappings

**Comment by DavidKnight247** [comment]
Try looking here:
https://github.com/ekeeke/Genesis-Plus-GX/blob/ae28f874021d92f0abd37113a56dcec89b570777/core/cart_hw/sms_cart.c

**Comment by kamotswind** [comment]
Looking over that list and doing some more research I downloaded a ROM named: Aerial Assault (Japan) (Rev 1).gg

I never thought to try a ROM that said it was for the Japan region only. However, everything is still in English and it works perfectly. It may be the one labeled "World" has slightly different code that just doesn't work with the current emulator. I think it is safe to say this is a ROM issue and not really something that should be fixed in the emulator right now. I'm going to close this issue but it can always been re-opened if other ROMs are reported to have a similar issue.

**Comment by OtherCrashOverride** [comment]
Stay tuned.

**Comment by OtherCrashOverride** [comment]
This should now work with the latest release:
https://github.com/OtherCrashOverride/go-play/releases/tag/20180718-smsplusgx

**Comment by kamotswind** [comment]
It does, thanks!
