### ISSUE TITLE
[GBC] Looney Tunes Collector - Martian Alert! sprite  truncated

### ISSUE THREAD

**Issue by puggile** [OtherCrashOverride/go-play#41]
I've noticed a truncated sprite in Looney Tunes Collector - Martian Alert! for GBC

I don't know if the same problem of #38 
To see issue, load save state and look at the hedgehog's animation.

File save:
[Looney Tunes Collector - Martian Alert! (Europe) (En,Fr,De,Es,It,Nl).gbc.sav.zip](https://github.com/OtherCrashOverride/go-play/files/2194809/Looney.Tunes.Collector.-.Martian.Alert.Europe.En.Fr.De.Es.It.Nl.gbc.sav.zip)
fw version: 20180712

**Comment by OtherCrashOverride** [comment]
After loading the game with the patched firmware, the hedgehog is restored to normal by leaving the screen and returning.

**Comment by puggile** [comment]
Ok, thanks for reply
