### ISSUE TITLE
[GB/GBC] Frameskip issue

### ISSUE THREAD

**Issue by TXIDRIVR** [OtherCrashOverride/go-play#55]
It seem that frameskip have been set to 1 (or 2...). Could we set it to 0 instead ? I can give games examples if you need. I use the latest firmware 20180726 with 20180726-smsplusgx.

**Comment by OtherCrashOverride** [comment]
The LCD can only operate up to 30fps.  The emulators operate at 60fps.  Therefore, its necessary to skip frames.

**Comment by TXIDRIVR** [comment]
Thanks for your reply. 

I saw on hardkernel.com that you sell LCD spare parts. Will you sell a 60FPS one ? Or do you plan to make a Odroid-Go revision a new LCD ?

Thanks again.

**Comment by OtherCrashOverride** [comment]
I do not sell anything. You will need to contact HardKernel about their product plans.
