### ISSUE TITLE
[Request] gba support

### ISSUE THREAD

**Issue by tsndr** [OtherCrashOverride/go-play#56]
Shouldn't the odroid-go be able to handle gba games, and is it possible to add support? 😊

**Comment by jpxdude** [comment]
No way, the ESP32 already struggles a bit with some NES and GBC emulation.  Even a Pi Zero struggles with GBA emulation, and that is certainly more powerful.

**Comment by tsndr** [comment]
Oh, ok, just wanted to ask. Thanks for the quick reply 😊
