### ISSUE TITLE
Game list locks up in new version when many games are present for the system

### ISSUE THREAD

**Issue by wvdschel** [OtherCrashOverride/go-play#59]
I have recently upgrade to the following versions:

- [Firmware 20180727](https://github.com/OtherCrashOverride/odroid-go-firmware/releases/tag/20180727)
- [Go Play 20180726-smsplusgx](https://github.com/OtherCrashOverride/go-play/releases/tag/20180726-smsplusgx)

On my SD card I have a couple of hundred Game Boy ROMS, and the system locks up when I try to open the list. It worked fine before.

**Comment by OtherCrashOverride** [comment]
This likely due to the change in file sorting.  Previously, the order was numeric: "B" < "a".  Now the order is case insensitive: "B" > "a".

I mentioned on the forum:
> Since the file list is sorted, it is necessary to load all the file names into memory. After this a 'quick sort' is performed. This algorithm, like all fast sorts, is recursive: it takes more memory depending on how 'unsorted' the list is. Deleting and re-copying games changes this 'natural order' and that is why it affects success. Adding, erasing, or renaming a file will also affect success.

Testing is done with 2,724 NES files, 1,424 GBC files, and 1,609 GB files.

**Comment by OtherCrashOverride** [comment]
The 20180810 release should address this.

**Comment by de-wim** [comment]
Confirmed fixed :+1:
