### ISSUE TITLE
Can't open .sav file with mGBA

### ISSUE THREAD

**Issue by tsndr** [OtherCrashOverride/go-play#65]
I just tried to load my savegame on pc (for a .gb-game) and it didn't work. Is there any possibility to convert the savegame to work with mGBA or other emulators?

**Comment by kamotswind** [comment]
It is technically possible for someone to make a conversion tool, but there isn't one currently. In the future someone may even adjust the way the game saves work so they can be used with other emulators. It is all open source so anyone can try :)

**Comment by OtherCrashOverride** [comment]
This is discussed here:
https://forum.odroid.com/viewtopic.php?f=158&t=31751

Save games to/from other systems/emulators are not supported.
