### ISSUE TITLE
Guide to build the FW file

### ISSUE THREAD

**Issue by pmprog** [OtherCrashOverride/go-play#71]
Sorry if this is a bit of a dumb question, but how do you build the .FW file to go on the SD card?

I set up a Lubuntu VMwith the following esp-idf, xtensa-esp32-elf and your odroid go repos.
When I did make in "doom-odroid-go", it created a build directory with a number of files and directories
When I did go-play/odroid-go-common, I got asked a number of questions (that I didn't know what to answer, so I left the defaults?), and again have ended up with a build folder with files and directories

These build directories have two .bin files, an .elf, and a .map; and lots of folders that look like library code/objects; but not a FW file I can put on the SD card.

TIA

**Comment by explit28** [comment]
Another question: Are you going to build a Firmware with Doom integrated into the standard Odroid-FW (With the stock Emulators) ?

**Comment by devsaurus** [comment]
See https://github.com/23pieces/Odroid-Go-Tools. That built a good `Go-Play.fw` file for me.

**Comment by pmprog** [comment]
@devsaurus thanks, I'll take a look at that

**Comment by explit28** [comment]
I'm not really a dev. and building and compiling is a bit complicated for me.
If someone could send me his ready .fw file - it would be awesome.

1000sun (at) mailbox.org

Thanks

**Comment by pmprog** [comment]
@explit7 Why don't you just download it from the official ODroid Go wiki?

**Comment by explit28** [comment]
Hi,
I have already the stock odroid firmware from 10.08.2018 downloaded, but i want a fw, where doom and (maybe) other emulators are integrated in the Game Menu



On Saturday, 29 September 2018, Marq Watkin wrote:
> @explit7 Why don't you just download it from the official ODroid Go wiki?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/OtherCrashOverride/go-play/issues/71#issuecomment-42566789

-- 
Kind regards / 
Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski

**Comment by yoursunny** [comment]
> If someone could send me his ready .fw file - it would be awesome.

They are on “releases” page of each repository, such as 
https://github.com/OtherCrashOverride/doom-odroid-go/releases

**Comment by explit28** [comment]
Thanks, as i understand this is standalone doom.fw

I have it already.
I was hoping, someone could integrate doom in the main Odroid-Go FW, 
so it is not necessary to flash doom.fw and than back to adroid-go.fw

 

On Sunday, 30 September 2018, Junxiao Shi wrote:
> > If someone could send me his ready .fw file - it would be awesome.
> 
> They are on “releases” page of each repository, such as 
> https://github.com/OtherCrashOverride/doom-odroid-go/releases
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/OtherCrashOverride/go-play/issues/71#issuecomment-42571645

-- 
Kind regards / 
Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski

**Comment by shar33f** [comment]
+1

**Comment by yoursunny** [comment]
> integrate doom in the main Odroid-Go FW

That'll be difficult because Doom has a big WAD in the flash, and the program does not support reading the WAD from SD card.

> it is not necessary to flash doom.fw and than back to adroid-go.fw

Flashing isn't really a concern. The flash is rated for at least 10000 cycles. If you flash once per hour, it lasts more than a year.

**Comment by OtherCrashOverride** [comment]
> how do you build the .FW file to go on the SD card?

This is not supported for Go-Play.  For Doom, it is documented on the release page.

There are currently no plans to integrate Doom into Go-Play.  It has not reached a level of maturity where its possible to integrate.  For example, after starting it, you could never return to the menu.  It would need to be playable (including sound and WAD support) before it would be considered.

**Comment by pmprog** [comment]
Thanks for the reply. I'll have a play with the doom release and see how I get on.
Cheers
