### ISSUE TITLE
Screen Resolution issue on latest release

### ISSUE THREAD

**Issue by dudesky71** [OtherCrashOverride/go-play#77]
Gameboy and Gameboy color do not render at full screen on the October (latest 20181004) release. It's 1/4 the size it should be.

**Comment by gentleben** [comment]
Hi. While playing a game have you tried holding down "Start" and then pressing right on the d-pad? That should switch scaling on/off.

**Comment by dudesky71** [comment]
I have not tried this but i will. I didn't realize this was an option. Where can i find a list of commands/controls for this type of thing? Thank You.

**Comment by gentleben** [comment]
This page on the Odroid-Go wiki lists how the various buttons work with go-play:

https://wiki.odroid.com/odroid_go/emulator/usage_go_play

**Comment by dudesky71** [comment]
Excellent. I saw that page but didn't scroll down to see all the details. Thank you :)

**Comment by gentleben** [comment]
No probs! :-)

**Comment by kamotswind** [comment]
@dudesky71 If this is resolved please close the issue :)

**Comment by dudesky71** [comment]
ok. no problem :)
