### ISSUE TITLE
Direct Usage w/o Odroid Go FW

### ISSUE THREAD

**Issue by 32teeth** [OtherCrashOverride/go-play#89]
# Direct Usage w/o Odroid Go FW
> Is there a way to use go-play without

## Use Case

1. Direct Flash of Go Play to ESP32
2. Direct Flash of only selected emulator

**Comment by OtherCrashOverride** [comment]
Each emulator is a regular esp-idf project.  You can do a 'make flash' build for stand alone operation.  However, at this time you will need to hardcode a file name to use (#79):
