### ISSUE TITLE
Repackaging Entire Go-Play firmware

### ISSUE THREAD

**Issue by 32teeth** [OtherCrashOverride/go-play#91]
Editing core odroid go display (and odroid common) to enable different TFT displays.
Have been able to create FW/BIN for each emulator.

No instructions on how to repackage entire Go-Play FW as single package

**Comment by pebri86** [comment]
It's possible to repack everything with different display driver except the launcher, Odroid Go Springboard is closed source, so you can repack but replace springboard with another launcher app from the forum. Go [here](https://wiki.odroid.com/odroid_go/arduino_app) to learn how to use mkfw to pack binary compiled to .fw file.

**Comment by 32teeth** [comment]
If i do a flash read of the springboard, can i repackage with that?

**Comment by pebri86** [comment]
Yes, you can repackage with that, but springboard compiled for odroid go hardware so if you use different TFT display, it won't work correctly because of different driver.

**Comment by 32teeth** [comment]
> Yes, you can repackage with that, but springboard compiled for odroid go hardware so if you use different TFT display, it won't work correctly because of different driver.

@OtherCrashOverride 
This is the problem i am currently encountering!




It would be nice if we could add different TFT drivers for Springboard

| Description | Results |
| ------------------ | ---------------- |
| ![IMG_0654](https://user-images.githubusercontent.com/75797/57878135-60ff3700-77e7-11e9-888e-321f365f3c7a.jpeg) | Launcher (needs display driver) |
| ![IMG_0655](https://user-images.githubusercontent.com/75797/57878176-74aa9d80-77e7-11e9-970d-4f7a905a0ff2.jpeg) | Game List  (needs display driver) |
| ![IMG_0656](https://user-images.githubusercontent.com/75797/57878197-82602300-77e7-11e9-973b-e7b23062896f.jpeg) | Game Select (needs display driver) |
| ![IMG_0657](https://user-images.githubusercontent.com/75797/57878224-90ae3f00-77e7-11e9-9735-909e9d3e0040.jpeg) | In Game (ALL GOOD) |
| ![IMG_0658](https://user-images.githubusercontent.com/75797/57878238-9a37a700-77e7-11e9-995b-da0a4c4f9406.jpeg) | ALL GOOD  |

**Comment by pebri86** [comment]
We have been talk at the forum for this issue for a while, the springboard is remain as closed source we couldn't do anything other than replace it with open source alternative that someone share on the forum. That's why i use go go launcher as base of my launcher.
